### ISSUE TITLE
Unnecessary URLs

### ISSUE THREAD

**Issue by yuriscosta** [Mazuh/mazuh.github.io#8]
These links above the favicons are useless. The favicons do the link's job.

**Comment by Mazuh** [comment]
It may not be clear enough that the icons are buttons.

**Comment by yuriscosta** [comment]
And why did you put the icons? Did you see in others sites links under the icons? When the user pass the mouse through the icon, the cursor will change.

**Comment by Mazuh** [comment]
Already tried to do it, but I failed. =( 
If you can (and will) make it work, I'll be glad glad for it. jajaja
